// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UploadDocumentEmailDocuments.Persistence;

namespace UploadDocumentEmailDocuments.Persistence.Migrations
{
    [DbContext(typeof(UploadDocumentEmailDocumentsDbContext))]
    [Migration("20220111125943_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UploadDocumentEmailDocuments.Domain.FilesDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersPersonalDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsersPersonalDetailId");

                    b.ToTable("FilesDetails");
                });

            modelBuilder.Entity("UploadDocumentEmailDocuments.Domain.UsersPersonalDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersPersonalDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = "20",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateLastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "steville2013@gmail.com",
                            Name = "Stephen",
                            Phone = "08077670500"
                        });
                });

            modelBuilder.Entity("UploadDocumentEmailDocuments.Domain.FilesDetail", b =>
                {
                    b.HasOne("UploadDocumentEmailDocuments.Domain.UsersPersonalDetail", "UsersPersonalDetail")
                        .WithMany("fileDetails")
                        .HasForeignKey("UsersPersonalDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsersPersonalDetail");
                });

            modelBuilder.Entity("UploadDocumentEmailDocuments.Domain.UsersPersonalDetail", b =>
                {
                    b.Navigation("fileDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
